CREATE TABLE IF NOT EXISTS likes (
    ID INT NOT NULL AUTO_INCREMENT,
    postID INT NOT NULL,
    authorID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (postID) REFERENCES posts(ID),
    FOREIGN KEY (authorID) REFERENCES users (ID)
);