CREATE TABLE IF NOT EXISTS posts (
    ID INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(2048) NOT NULL,
    allText TEXT NOT NULL,
    dateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    dateModified DATETIME ON UPDATE CURRENT_TIMESTAMP,
    imageURL VARCHAR(2048),
    authorID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (authorID) REFERENCES users (ID)
);